// ============================================================================
// GENERATED by scripts/gen-money-mirror.cjs — DO NOT EDIT BY HAND.
// Mirror of src/config/credits.ts, src/config/coins.ts and
// src/config/monetisation.ts for the Deno edge functions, so the server grants
// exactly what the UI advertises. Re-run the generator after changing a config.
//
// Money model summary (see MONEY.md):
//   1 credit = 7.5 coins
//   best credit pack      $0.03845/credit  → $0.00513/coin if converted
//   top coin bundle       $0.00500/coin     (beats converting: coins for cash are the better deal)
//   first-purchase bundle $0.00284/coin             (best rate in the app, one per account)
// ============================================================================

export const COINS_PER_CREDIT = 7.5;

export interface CreditPack { id: string; credits: number; bonus: number; price_cents: number; label?: string }
export interface CoinBundle { id: string; coins: number; bonus: number; price_cents: number; label?: string; best_value?: boolean }
export interface UnlimitedPack { id: string; price_cents: number; period: "lifetime" | "month" | "year"; label: string }

export const CREDIT_PACKS: CreditPack[] = [
  {
    "id": "pack_25",
    "credits": 25,
    "bonus": 0,
    "price_cents": 249,
    "label": "Starter"
  },
  {
    "id": "pack_50",
    "credits": 50,
    "bonus": 10,
    "price_cents": 499,
    "label": "Boost"
  },
  {
    "id": "pack_120",
    "credits": 120,
    "bonus": 25,
    "price_cents": 999,
    "label": "Popular"
  },
  {
    "id": "pack_200",
    "credits": 200,
    "bonus": 50,
    "price_cents": 1499,
    "label": "Power"
  },
  {
    "id": "pack_500",
    "credits": 500,
    "bonus": 150,
    "price_cents": 2499,
    "label": "Max"
  }
];

export const COIN_BUNDLES: CoinBundle[] = [
  {
    "id": "coins_120",
    "coins": 120,
    "bonus": 0,
    "price_cents": 299,
    "label": "Starter"
  },
  {
    "id": "coins_300",
    "coins": 300,
    "bonus": 30,
    "price_cents": 599,
    "label": "Value"
  },
  {
    "id": "coins_800",
    "coins": 800,
    "bonus": 120,
    "price_cents": 1299,
    "label": "Popular"
  },
  {
    "id": "coins_2000",
    "coins": 2000,
    "bonus": 500,
    "price_cents": 2499,
    "label": "Pro"
  },
  {
    "id": "coins_5000",
    "coins": 5000,
    "bonus": 2500,
    "price_cents": 3749,
    "label": "Mega"
  }
];

/** Sold once per account — the edge function checks user_purchases first. */
export const FIRST_PURCHASE_BUNDLE: CoinBundle = {
  "id": "coins_first",
  "coins": 700,
  "bonus": 0,
  "price_cents": 199,
  "label": "First buy · one only"
};

export const UNLIMITED_PACKS: UnlimitedPack[] = [
  {
    "id": "infinite_lifetime",
    "price_cents": 4999,
    "period": "lifetime",
    "label": "Lifetime"
  },
  {
    "id": "infinite_monthly",
    "price_cents": 299,
    "period": "month",
    "label": "Monthly"
  },
  {
    "id": "infinite_yearly",
    "price_cents": 2499,
    "period": "year",
    "label": "Yearly"
  }
];

export const DEPRECATED_PRODUCT_IDS: string[] = [
  "sub_minimum_monthly",
  "sub_premium_monthly",
  "sub_pro_monthly",
  "sub_pro_yearly",
  "sub_elite_monthly",
  "sub_elite_yearly",
  "plan_free",
  "plan_minimum",
  "plan_pro",
  "plan_elite",
  "minimum",
  "pro",
  "elite",
  "premium",
  "sub_minimum_monthly",
  "Minimum Plan",
  "subscription",
  "deprecated",
  "month",
  "Replaced in Phase 2 by the new credit subscription.",
  "sub_premium_monthly",
  "Premium Plan",
  "subscription",
  "deprecated",
  "month",
  "Replaced in Phase 2 by the unlimited option.",
  "plan_pro",
  "Pro tier",
  "subscription",
  "deprecated",
  "month",
  "Tier-based gating removed; features now credit-based.",
  "plan_elite",
  "Elite tier",
  "subscription",
  "deprecated",
  "month",
  "Tier-based gating removed; features now credit-based."
];

/** Retired credit products, honoured only so older baskets still check out. */
export const LEGACY_CREDIT_PACKS: CreditPack[] = [
  {
    "id": "credits_20",
    "credits": 20,
    "bonus": 0,
    "price_cents": 500,
    "label": "Legacy 20"
  },
  {
    "id": "credits_50",
    "credits": 50,
    "bonus": 0,
    "price_cents": 1250,
    "label": "Legacy 50"
  },
  {
    "id": "credits_100",
    "credits": 100,
    "bonus": 0,
    "price_cents": 2500,
    "label": "Legacy 100"
  },
  {
    "id": "credits_200",
    "credits": 200,
    "bonus": 0,
    "price_cents": 5000,
    "label": "Legacy 200"
  }
];

/**
 * Purchasable entitlement products → the key public.credit_cost() expects.
 * The PRICE always comes from the database (economy_config.feature_costs), never
 * from here, so the client, the database and the edge function agree.
 */
export const FEATURE_PRODUCTS: Record<string, string> = {
  "archetype": "archetype_view",
  "cross_sport": "cross_sport_unlock",
  "form_analysis": "form_analysis_unlock",
  "injury_management": "injury_management_unlock",
  "mental_gym": "mental_gym_unlock",
  "nutrition_pack": "nutrition_pack_unlock"
};

/** Product id → coins granted (base + bonus), including the first-purchase bundle. */
export const COIN_GRANTS: Record<string, number> = {
  "coins_120": 120,
  "coins_300": 330,
  "coins_800": 920,
  "coins_2000": 2500,
  "coins_5000": 7500,
  "coins_first": 700
};

/** Product id → credits granted (base + bonus). */
export const CREDIT_GRANTS: Record<string, number> = {
  "pack_25": 25,
  "pack_50": 60,
  "pack_120": 145,
  "pack_200": 250,
  "pack_500": 650,
  "credits_20": 20,
  "credits_50": 50,
  "credits_100": 100,
  "credits_200": 200
};

/** Product id → list price in cents, from the server tables only. */
export const PRODUCT_PRICES: Record<string, number> = {
  "pack_25": 249,
  "pack_50": 499,
  "pack_120": 999,
  "pack_200": 1499,
  "pack_500": 2499,
  "credits_20": 500,
  "credits_50": 1250,
  "credits_100": 2500,
  "credits_200": 5000,
  "coins_120": 299,
  "coins_300": 599,
  "coins_800": 1299,
  "coins_2000": 2499,
  "coins_5000": 3749,
  "coins_first": 199,
  "infinite_lifetime": 4999,
  "infinite_monthly": 299,
  "infinite_yearly": 2499
};

/** Products that may only ever be granted once per account. */
export const ONE_TIME_PRODUCTS: string[] = [FIRST_PURCHASE_BUNDLE.id];
